CREATE DATABASE IF NOT EXISTS taskAPI;

USE taskAPI;

CREATE TABLE tarefas(
	id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    descricao VARCHAR(500) NOT NULL,
    concluida BOOLEAN NOT NULL DEFAULT false
);
